### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by desuto** [naz013/awesome-calendar-android#2]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by naz013** [comment]
Feel free to contribute.

P.S. This project is not completed.

**Comment by desuto** [comment]
I have designed the logo for awesome calendar. And this is the result of design. what do you think?
If there's something you want to change, let me know
![awesome calendar](https://user-images.githubusercontent.com/39637790/40628297-5a1677be-62ee-11e8-94fa-231764577a23.png)

**Comment by naz013** [comment]
It nice. You can include it to readme description.

**Comment by desuto** [comment]
I have uploaded all the files in this link.
https://drive.google.com/drive/u/0/folders/1Q2KDzN1RGZq8VNZWz7s8tQ0ozdow3pux

and I have also sent pull requests. please check.

**Comment by naz013** [comment]
#3 Merged.
